### ISSUE TITLE
Error when processing with enum embedded in message

### ISSUE THREAD

**Issue by yijiasu** [agreatfool/grpc_tools_node_protoc_ts#23]
See https://github.com/improbable-eng/ts-protoc-gen/issues/14

This repo also have this issue, when generating code with enum embedded in message, error occurs.

```
protoc-gen-ts error: Error: No enum export for: UserVerifyReply.ReturnCode
    at descriptor.getFieldList.forEach (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/lib/format/partial/MessageFormatter.js:122:27)
    at Array.forEach (<anonymous>)
    at Object.format (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/lib/format/partial/MessageFormatter.js:60:35)
    at descriptor.getMessageTypeList.forEach.enumType (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/lib/format/ProtoMsgTsdFormatter.js:35:63)
    at Array.forEach (<anonymous>)
    at Object.format (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/lib/format/ProtoMsgTsdFormatter.js:34:41)
    at codeGenRequest.getFileToGenerateList.forEach.fileName (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/index.js:32:79)
    at Array.forEach (<anonymous>)
    at Utility_1.Utility.withAllStdIn (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/index.js:27:48)
    at Socket.<anonymous> (/Users/suyijia/Documents/iOS/***/node_modules/grpc_tools_node_protoc_ts/build/lib/Utility.js:68:13)

--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

**Comment by yijiasu** [comment]
I've created a pull request that resolved this issue. Please kindly check it and consider merging.

**Comment by agreatfool** [comment]
I have already tested this case at the beginning, and still cannot be reproduced.

Could you please confirm several versions, as listed below are all my versions:
```
node --version
v8.4.0
npm --version
5.2.0
protoc --version
libprotoc 3.3.0
grpc_tools_node_protoc --version
libprotoc 3.4.0
npm list -g --depth=0 | grep grpc-tools
grpc-tools@1.6.6
```

And also several version listed in the `examples/package.json`.

**Comment by yijiasu** [comment]
Thanks for your time. 

I will setup a environment you listed and try to reproduce the error. If it cannot reproduce I will check my own environment and see if there’s any difference that result in this error.
